### ISSUE TITLE
Feature: Add a capability to drop spans in span-normalizer based on some attribute:value criterion

### ISSUE THREAD

**Issue by buchi-busireddy** [hypertrace/hypertrace-ingester#121]
Use case:
---------
Very often, depending on the instrumentation libraries and agents, we will end up with a case where there are some spans that are getting generated from the agents but they're not really helpful for API observability or tracing. Although it's always good to have all raw traces, since they don't come for cheap, we would want to avoid processing data that's not really helpful.

It would be really helpful if we have the capability to drop some spans in the span-normalizer based on some criterion, which checks for attribute:value in the span.

**Comment by buchi-busireddy** [comment]
Fixed in https://github.com/hypertrace/hypertrace-ingester/commit/642dc0aaa9b33f4bfc52eb47ba0b7e0def19390b

**Comment by jcchavezs** [comment]
Hi @*buchi-busireddy <https://github.com/buchi-busireddy> I wonder the
reason for this was preferred to be added here over collector cc @davexroth*

**Comment by buchi-busireddy** [comment]
@jcchavezs Here are two reasons:
1. We're still in the process of moving OTel collector and doesn't make sense to add this feature in opencensus collector
2. It's usually better to have this kind of functionality at multiple levels. So, even if we want to add in collector later, it's okay to have in this layer too.
