### ISSUE TITLE
Migrate flink jobs in streaming pipeline to kafka-streams

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace-ingester#2]
Currently, our ingestion pipeline consists of `span-normalizer`, `raw-spans-grouper`, `hypertrace-trace-enricher`, and `hypertrace-views-generator`, which are flink jobs. This currently has some limitations.

Migrating to kafka-streams can help addressing some of the problems regarding cluster maintenance.  

`Note:` Migration to kafka-stream has already started. so we will be using this issue to track the progress.

- [x] https://github.com/hypertrace/span-normalizer
- [x] https://github.com/hypertrace/raw-spans-grouper
- [x] https://github.com/hypertrace/hypertrace-trace-enricher
- [x] https://github.com/hypertrace/hypertrace-view-generator

**Comment by kotharironak** [comment]
This changes will need - https://github.com/hypertrace/kafka-streams-framework/issues/5

**Comment by adriancole** [comment]
I think this is done?

**Comment by kotharironak** [comment]
Yes, closing this one.
