### ISSUE TITLE
Spankind instead of SpanTypes in our spans 

### ISSUE THREAD

**Issue by rish691** [hypertrace/hypertrace-ingester#72]
OTel uses the term SpanKind instead of SpanType and also has its own enum values. To be aligned with OTel in the long run, we should also start using SpanKind instead of SpanType. If renaming the existing field isn't possible or is more work, we should introduce a new field and slowly move all consumers to this new field.

Not sure if it is still needed? 

cc @kotharironak @buchi-busireddy

**Comment by kotharironak** [comment]
SPAN_TYPE is our enriched attribute name which is internal to identify `entry` and `exit` relation from SpanKind raw attributes. I think it makes sense to have different names.

**Comment by kotharironak** [comment]
Closing this, pl. reopen if it doesn't make sense and if we still think need it to change.
